function New-UnifiSite {
    <#
    .SYNOPSIS
        Creates a new site on the UniFi Controller.

    .DESCRIPTION
        Creates a new site with the specified description (display name).
        The internal site name is auto-generated by the controller.

    .PARAMETER Description
        The display name/description for the new site.
        This is what appears in the UI.

    .EXAMPLE
        New-UnifiSite -Description 'Client ABC - Main Office'

    .EXAMPLE
        'Site A', 'Site B', 'Site C' | ForEach-Object { New-UnifiSite -Description $_ }

    .OUTPUTS
        PSCustomObject. The created site object with name (internal) and desc (display name).

    .NOTES
        Requires an active UniFi session. Use Connect-Unifi first.
        The internal site name is auto-generated and returned in the response.
    #>
    [CmdletBinding(SupportsShouldProcess)]
    [OutputType([PSCustomObject])]
    param(
        [Parameter(Mandatory, ValueFromPipeline)]
        [ValidateNotNullOrEmpty()]
        [Alias('Name', 'SiteName')]
        [string]$Description
    )

    process {
        $Body = @{
            cmd  = 'add-site'
            desc = $Description
        }

        if ($PSCmdlet.ShouldProcess($Description, 'Create site')) {
            # Site creation goes to cmd/sitemgr on the default site
            Invoke-UnifiApi -Endpoint 'cmd/sitemgr' -SiteName 'default' -Method Post -Body $Body
        }
    }
}
